version: "3"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    restart: always
    expose:
      - "3000"
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - server
