version: "3"

services:
  server:
    image: ghcr.io/tesso57/web-speed-hackathon-2022/server:latest
    build:
      context: .
      dockerfile: Dockerfile.server
    restart: always
    expose:
      - "3000"
  client:
    image: ghcr.io/tesso57/web-speed-hackathon-2022/client:latest
    build:
      context: .
      dockerfile: Dockerfile.client
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - server
